app/cs3450/cs3450/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('moneyLawndering/', include('moneyLawndering.urls')),
]

app/cs3450/moneyLawndering/urls.py
from django.urls import path

from . import views

app_name = 'moneyLawndering'
urlpatterns = [
    path('', views.index, name='signin'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('createuser/', views.createUser, name='createUser'),
    path('updateuser/', views.updateUser, name='updateUser'),
    path('account/', views.account, name='account'),
    path('publiclistings/', views.publicListing, name='publicListing'),
    path('<int:listing_id>/acceptlisting/', views.acceptListing, name='acceptListing'),
    path('mylistings/', views.myListing, name='myListing'),
    path('<int:listing_id>/updateListing/', views.updateListing, name='updateListing'),
    path('<int:listing_id>/deleteListing/', views.deleteListing, name='deleteListing'),
    path('createListing/', views.createListing, name='createListing'),
    path('newListing/', views.newListing, name='newListing'),
    path('acceptedjobs/', views.acceptedJobs, name='acceptedJobs'),
    path('directtransfer/', views.directTransfer, name='directTransfer'),
    path('history/', views.history , name='history'),
    path('<int:listing_id>/applicantlist/', views.applicantList, name='applicantlist'),
    path('acceptapplicant/<int:listing_id>/<int:worker_id>', views.acceptApplicant, name='acceptApplicant'),
    path('completedJob/<int:listing_id>', views.completedJob, name='completedJob'),
    path('admin/', views.admin, name='admin'),
    path('customerreview/<int:listing_id>', views.customerReview, name='customerReview'),
    path('sendMoney/', views.sendMoney, name='sendMoney'),
    path('categories/', views.categories, name='category'),
    path('createCategory/', views.createCategory, name='createCategory'),
    path('deleteCategory/<int:category_id>/', views.deleteCategory, name='deleteCategory'),
    path('workerreviews/<int:listing_id>/<int:worker_id>/', views.workerReviews, name='workerreviews')
]

app/cs3450/moneyLawndering/models.py
from django.db import models
import datetime
from django.utils import timezone

class User(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    type = models.IntegerField()  # 0 for worker, 1 for customer, 2 for admin
    password = models.CharField(max_length=200)
    phoneNumber = models.IntegerField()
    address = models.CharField(max_length=200)
    accountBalance = models.FloatField()
    rating = models.IntegerField(default=5)

    def __str__(self):
        return self.name

    def isWorker(self):
        return self.type == 0

    def isCustomer(self):
        return self.type == 1

    def isAdmin(self):
        return self.type == 2
    


class Listing(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=200)
    location = models.CharField(max_length=300)
    time_est = models.FloatField()
    dayOfWeek = models.CharField(max_length=100)
    startTimeOfDay = models.CharField(max_length=100)
    endTimeOfDay = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    status = models.IntegerField()  # 0=open, 1=closed, 2=accepted, 3=pending, 4=completedForWorker 5=completedForCustomer
    worker = models.IntegerField()
    workerPhoneNumber = models.IntegerField()
    workername = models.CharField(max_length=100)
    pubDate = models.DateTimeField('date published')

    def __str__(self):
        return self.customer.name

    def wasPublishedRecently(self):
        return self.pubDate >= timezone.now() - datetime.timedelta(days=1)

    def isOpen(self):
        return self.status == 0

    def isClosed(self):
        return self.status == 1

    def isAccepted(self):
        return self.status == 2

    def isPending(self):
        return self.status == 3

    def isCompleted(self):
        return self.status == 4

    
    

class AppliedFor(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="applicants")
    worker = models.IntegerField()


#reviews left by the worker for the customer
class CustomerReview(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    worker = models.IntegerField()
    rating = models.IntegerField()
    description = models.TextField()


#reviews left by the customer for the worker
class WorkerReview(models.Model):
    customer = models.IntegerField()
    worker = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    description = models.TextField()


class Category(models.Model):
    type = models.CharField(max_length=300)

    def __str__(self):
        return self.type

app/cs3450/moneyLawndering/views.py
from ctypes import addressof
import email
from django.utils import timezone
from unicodedata import category, name
from django.forms import PasswordInput
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.http import Http404
from django.urls import reverse

from moneyLawndering.models import User, Listing, AppliedFor, CustomerReview, WorkerReview, Category

def index(request):
    return render(request, 'moneyLawndering/signin.html')

def signup(request):
    return render(request, 'moneyLawndering/signup.html')

def createUser(request):
    try:
        user = User.objects.get(email=request.POST['email'])
    except(KeyError, User.DoesNotExist) :
        name = request.POST['name']
        email = request.POST['email']
        type = request.POST['type']
        password = request.POST['password']
        phoneNumber = request.POST['phoneNumber']
        address = request.POST['address']
        accountBalance = request.POST['accountBalance']
        user = User(
            name = name,
            email = email,
            type = type,
            password = password,
            phoneNumber = phoneNumber,
            address = address,
            accountBalance = accountBalance,
        )
        user.save()
        request.session['userId'] = user.id
        return HttpResponseRedirect(reverse('moneyLawndering:account'))
    else:
        response = {
        "error": "User with corresponding email already exists",
        }
        response = JsonResponse(response)
        response['Access-Control-Allow-Origin'] = '*'
        return response


def signin(request):
    try:
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.get(email=email, password=password)
        request.session['userId'] = user.id
    except(KeyError, User.DoesNotExist):
        return render(request, 'moneyLawndering/signin.html', {'error_message' : 'Email and/or Password doesn\'t correspond to any existing user'})
    else:
        if user.isAdmin():
            return HttpResponseRedirect(reverse('moneyLawndering:admin'))
        else:
            return HttpResponseRedirect(reverse('moneyLawndering:account'))

def updateUser(request):
    user_id = request.session['userId']
    user = get_object_or_404(User, pk=user_id)
    user.name = request.POST['name']
    user.email = request.POST['email']
    user.password = request.POST['password']
    user.phoneNumber = request.POST['phoneNumber']
    user.address = request.POST['address']
    user.accountBalance = request.POST['accountBalance']
    user.save()
    return HttpResponseRedirect(reverse('moneyLawndering:account'))


def account(request):
    user_id = request.session['userId']
    user = get_object_or_404(User, pk=user_id)
    reviews = []
    if user.type == 0:
        reviews = WorkerReview.objects.filter(worker=user)
        for review in reviews:
            review.customer = User.objects.get(pk=review.customer)
        isWorker = True
    elif user.type == 1:
        reviews = CustomerReview.objects.filter(customer=user)
        for review in reviews:
            review.worker = User.objects.get(pk=review.worker)
        isWorker = False
    else:
        isWorker = False

    context = {'user': user, 'reviews': reviews, 'isWorker': isWorker}
    return render(request, 'moneyLawndering/account.html', context)


def publicListing(request):
    user_id = request.session['userId']
    user = get_object_or_404(User, pk=user_id)
    if(user.type == 1):
        response = {
        "failure": "You are not a worker and do not have access to this page",
        "user_id": user_id,
        "user_name": user.name,
        "isCustomer": user.type,
        }
        response = JsonResponse(response)
        response['Access-Control-Allow-Origin'] = '*'
        return response
    #this means that they are not a worker
    listings = Listing.objects.all().order_by('-pubDate')
    realListings = []
    for listing in listings:
        if(listing.status == 0 or listing.status == 3):
            realListings.append(listing)
            
    context = {'listings' : realListings,
                'user': user}
    return render(request, 'moneyLawndering/publicListing.html', context)

def acceptListing(request, listing_id):
    user_id = request.session['userId']
    #first make sure that they have posted a listing
    try:
        listing = Listing.objects.get(pk=listing_id)
    except(KeyError, Listing.DoesNotExist) :
        raise Http404("Listing does not exist here jose")
    listing = Listing.objects.get(pk=listing_id)
    try:
        listing.applicants.get(worker=user_id)
    except(KeyError, AppliedFor.DoesNotExist) :
        listing.applicants.create(worker=user_id)
        #set the status = 3 because the listing is now pending
        listing.status = 3
        listing.save()
    return HttpResponseRedirect(reverse('moneyLawndering:publicListing'))

    


def myListing(request):
    user_id = request.session['userId']
    user = get_object_or_404(User, pk=user_id)
    if user.type == 0:
        raise Http404("You are not a customer and therefore do not have access to the accepted jobs page")
    #first get all listing that are just open
    openListing = user.listing_set.filter(status=0)

    #get all listings that are pending
    applicantsList = []
    pendingListing = user.listing_set.filter(status=3)
    for listing in pendingListing:
        applicantsList.append(len(listing.applicants.all()))
    #applicantsList should be an array that has the amount of people who have applied to each listing

    #get all listings that have a worker but not completed
    acceptedListing = user.listing_set.filter(status=2)

    #get all listings that have worker that completed the job but hasnt left a review
    completedListing = user.listing_set.filter(status=4)

    pendingListingSize = []
    for i in range(len(pendingListing)):
        pendingListingSize.append(i)

    categories = Category.objects.all()

    return render(request, 'moneyLawndering/myListing.html', {
            'openListing': openListing,
            'pendingListing': pendingListing,
            'pendingListingSize': pendingListingSize,
            'applicantsList': applicantsList,
            'acceptedListing': acceptedListing,
            'completedListing': completedListing,
            'categories': categories,
            'user': user,
        })

def customerReview(request, listing_id):
    user_id = request.session['userId']
    listing = get_object_or_404(Listing, pk=listing_id)
    listing.status = 5
    listing.save()
    customer = get_object_or_404(User, pk=user_id)
    worker = get_object_or_404(User, pk=listing.worker)
    admin = get_object_or_404(User, type=2)

    # transfer the money now
    admin.accountBalance = admin.accountBalance + listing.price * .1
    worker.accountBalance = worker.accountBalance + listing.price * .9
    customer.accountBalance = customer.accountBalance - listing.price
    worker.save()
    customer.save()
    admin.save()

    workerReview = worker.workerreview_set.create(
        customer = customer.id,
        rating = request.POST['rating'],
        description = request.POST['review']
    )
    workerReview.save()

    #reset the workers rating
    workerReviews = worker.workerreview_set.all()
    overallRating = 0
    for review in workerReviews:
        overallRating = overallRating + review.rating
    overallRating = overallRating // len(workerReviews)
    worker.rating = overallRating
    worker.save()

    return HttpResponseRedirect(reverse('moneyLawndering:myListing'))
    
def applicantList(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    customerId = listing.customer.id
    user = get_object_or_404(User,pk=customerId)
    applications = listing.applicants.all()
    users = []
    for application in applications:
        users.append(User.objects.get(pk=application.worker))
    context = {'listing': listing, 'users': users, 'user': user}
    return render(request, "moneyLawndering/listApplicants.html", context)

def workerReviews(request, listing_id, worker_id):
    worker = get_object_or_404(User, pk=worker_id)
    listing = get_object_or_404(Listing, pk=listing_id)
    user = get_object_or_404(User, pk=listing.customer.id)
    reviews = worker.workerreview_set.all()
    for review in reviews:
        review.customer = User.objects.get(pk=review.customer)
    context = {'listing': listing, 'worker': worker, 'reviews': reviews, 'user':user}
    return render(request, "moneyLawndering/workerReviews.html", context)

def acceptApplicant(request, listing_id, worker_id):
    worker = get_object_or_404(User, pk=worker_id)
    listing = get_object_or_404(Listing, pk=listing_id)
    listing.worker = worker_id
    listing.workername = worker.name
    listing.workerPhoneNumber = worker.phoneNumber;
    listing.status=2
    listing.save()
    return HttpResponseRedirect(reverse('moneyLawndering:myListing'))


def createListing(request):
    user_id = request.session['userId']
    user = get_object_or_404(User, pk=user_id)
    categories = Category.objects.all()
    return render(request, "moneyLawndering/createListing.html", {'user':user, 'categories':categories})

def updateListing(request, listing_id):
    user_id = request.session['userId']
    user = get_object_or_404(User, pk=user_id)
    listing = get_object_or_404(Listing, pk=listing_id)
    if user_id == listing.customer_id:
        listing.category = request.POST['category']
        listing.location = request.POST['location']
        listing.time_est = request.POST['time_est']
        listing.dayOfWeek = request.POST['dayOfWeek']
        listing.startTimeOfDay = request.POST['startTime']
        listing.endTimeOfDay = request.POST['endTime']

app/cs3450/moneyLawndering/templates/moneyLawndering/categories.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Categories</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
        {% load static %}
        <link rel="shortcut icon" type="image/png" href="{% static 'moneyLawndering/favicon.ico' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'moneyLawndering/style.css' %}">
    </head>
	<body class="normal-page-background">
		<header>
			<div class="container-sm">
				<div class="row navBar pl-3 d-flex justify-content-between">
					<div class="navbar centered">
						<img class="col logoHeader d-none d-md-block" src="{% static 'moneyLawndering/ML-logo.png' %}" alt="MoneyLawndering Logo">
						<div class="col mr-2 grow"><div><a class="text-white" href="{% url 'moneyLawndering:account' %}">Account</a></div></div>
						{% if user.type == 0 %}
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:publicListing' %}">Public <br>Listings</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:acceptedJobs' %}">Accepted <br>Jobs</a></div></div>
						{% elif user.type == 1 %}
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:myListing' %}">Your <br>Listings</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:createListing' %}">New <br>Listing</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:directTransfer' %}">Direct <br>Transfer</a></div></div>
						{% elif user.type == 2 %}
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:admin' %}">Admin</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:publicListing' %}">Public <br>Listings</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:category' %}"><b>Categories</b></a></div></div>
						{% endif %}
						<div class="col grow"><div><a class="text-white" href="{% url 'moneyLawndering:history' %}">History</a></div></div>
					</div>
					<div class="navbar d-flex justify-content-end">
						<div class="col mr-2 text-warning grow"><div><a class="text-warning" href="{% url 'moneyLawndering:logout' %}">Log Out</a></div></div>
					</div>
				</div>
			</div>
		</header>
		<div class='fix'>
        <div class="container d-flex justify-content-center">
            <div class="card loginContents blurred m-4 w-50">
                <div class="text-center">
                    <h3 class="loginItem"><b>Create a category</b></h3>
                    <form action="{% url 'moneyLawndering:createCategory' %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <div class="form-floating">
                            <label for="category" class="form-label">Category: </label><br>
                            <input type="text" name="category" id="category" class="form-control" value=""><br>
                        </div>
                        <input type="submit" class="btn btn-primary loginItem" value="Submit"/>
                    </form>
                </div><hr>

                <h3 class="text-center"><b>Categories</b></h3>
                <ul>
                    {% for category in categories %}
                        <li class="mt-3 mb-3">
                            <form action="{% url 'moneyLawndering:deleteCategory' category.id %}" method="get">
                                {% csrf_token %}
                                {{ form }}
                                <label for="delete{{ category.id }}">{{category.type}}: </label>
                                <input type="submit" class="btn btn-danger float-right ml-2" id="delete{{ category.id }}" value="Delete"/> <br/>
                            </form>
                        </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
		</div>
		<footer>
			<div class="container-sm">
				<div class="row py-3 bg-light">
					<div class="w-100 mt-2 d-flex justify-content-end">
						<span class="social-text">Follow us!</span>
						<span class="social-icon social-box social-facebook"><i class="fa fa-facebook"></i></span>
						<span class="social-icon social-box social-instagram"><i class="fa fa-instagram"></i></span>
						<span class="social-icon social-box social-twitter"><i class="fa fa-twitter"></i></span>
						<span class="social-icon social-box social-twitter"><i class="fa fa-linkedin"></i></span>
					</div>
					<div class='text-muted ml-3'><p class="ml-3">© 2022 Group 6, Inc</p></div>
				</div>
			</div>
		</footer>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

app/cs3450/moneyLawndering/templates/moneyLawndering/listApplicants.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Applicants</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'moneyLawndering/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'moneyLawndering/style.css' %}">
</head>
	<body class="normal-page-background">
		<header>
			<div class="container-sm">
				<div class="row navBar pl-3 d-flex justify-content-between">
					<div class="navbar centered">
						<img class="col logoHeader d-none d-md-block" src="{% static 'moneyLawndering/ML-logo.png' %}" alt="MoneyLawndering Logo">
						<div class="col mr-2 grow"><div><a class="text-white" href="{% url 'moneyLawndering:account' %}">Account</a></div></div>
						{% if user.type == 0 %}
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:publicListing' %}">Public <br>Listings</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:acceptedJobs' %}">Accepted <br>Jobs</a></div></div>
						{% elif user.type == 1 %}
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:myListing' %}">Your <br>Listings</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:createListing' %}">New <br>Listing</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:directTransfer' %}">Direct <br>Transfer</a></div></div>
						{% elif user.type == 2 %}
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:admin' %}">Admin</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:publicListing' %}">Public <br>Listings</a></div></div>
							<div class="col mr-2 text-white grow"><div><a class="text-white" href="{% url 'moneyLawndering:category' %}">Categories</a></div></div>
						{% endif %}
						<div class="col grow"><div><a class="text-white" href="{% url 'moneyLawndering:history' %}">History</a></div></div>
					</div>
					<div class="navbar d-flex justify-content-end">
						<div class="col mr-2 text-warning grow"><div><a class="text-warning" href="{% url 'moneyLawndering:logout' %}">Log Out</a></div></div>
					</div>
				</div>
			</div>
		</header>
	<div class='fix'>
    <div class="container d-flex justify-content-center loginItem">
        <div class="card loginContents blurred m-3 w-50 text-center">
            <h1 class="mb-4">Applicants</h1>
			<form action="{% url 'moneyLawndering:myListing' %}" method="get">
				<input class="btn btn-success loginItem" type="submit" value="Go Back">
			</form><hr>
            {% for u in users %}
                <form action="{% url 'moneyLawndering:acceptApplicant' listing.id u.id %}" method="get">
                    {% csrf_token %}
                    {{ form }}
                    <div class="form-floating loginItem">
                        <label for="name"><b>Name:</b></label>
                        <p id="name">{{u.name|capfirst}}</p>
                    </div>
                    <div class="form-floating loginItem">
                        <label for="rating"><b>Rating:</b></label>
                        <p id="rating">{{u.rating}}</p>
                    </div>
                    <div class="form-floating loginItem">
                        <label for="link"><b>{{u.name|capfirst}}'s Reviews:</b></label>
                        <a id="link" href="{% url 'moneyLawndering:workerreviews'  listing.id u.id %}">See Reviews</a>
                    </div>
                    <input class="btn btn-primary loginItem" type="submit" value="Accept">
                </form><hr>
            {% endfor %}
        </div>
    </div>
	</div>
		<footer>
			<div class="container-sm">
				<div class="row py-3 bg-light">
					<div class="w-100 mt-2 d-flex justify-content-end">
						<span class="social-text">Follow us!</span>
						<span class="social-icon social-box social-facebook"><i class="fa fa-facebook"></i></span>
						<span class="social-icon social-box social-instagram"><i class="fa fa-instagram"></i></span>
						<span class="social-icon social-box social-twitter"><i class="fa fa-twitter"></i></span>
						<span class="social-icon social-box social-twitter"><i class="fa fa-linkedin"></i></span>
					</div>
					<div class='text-muted ml-3'><p class="ml-3">© 2022 Group 6, Inc</p></div>
				</div>
			</div>
		</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>